### ISSUE TITLE
Include Dependencies in setup.py

### ISSUE THREAD

**Issue by travis-morton** [bvanelli/actualpy#31]
Need to include sqlmodel and cryptography

**Comment by bvanelli** [comment]
I always thought that this was managed by find_packages(), but I don't have much experience with packaging.

I'll assign this to the first-release milestone.

**Comment by travis-morton** [comment]
find_packages() is for finding packages in your project while install_requires is for dependencies https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#packages
