### ISSUE TITLE
Update transactions via api calls

### ISSUE THREAD

**Issue by esseti** [bvanelli/actualpy#40]
### Description

Is it possible to do something of this via the api?

https://github.com/actualbudget/actual/issues/3034#event-13468944383

i can download the list of transaction and i know how to parse the payee and the notes, but then:
- where should the new transaction be?
- and how do i commit the changes?

**Comment by bvanelli** [comment]
Hello, I don't if I fully understand what you want to do, but you basically want to change transactions based on a local regex? What makes this library unique is that you can change the objects freely and then commit the results just like you would on a normal database:

```python
from actual import Actual
from actual.queries import get_transactions


changed_payees = set()
with Actual(password="mypass", file="CSV Import") as actual:
    for transaction in get_transactions(actual.session):
        # change the transactions notes
        if transaction.notes is not None:
            transaction.notes = transaction.notes + " my suffix!"
        # change the payee name
        if transaction.payee and transaction.payee.name is not None:
            # check if this payee wasn't changed before yet
            if transaction.payee_id not in changed_payees:
                transaction.payee.name = transaction.payee.name + " my suffix!"
                changed_payees.add(transaction.payee_id)
    # commit your changes!
    actual.commit()
```

I used the example CSV Import from the examples folder as a reference. Here is the before transactions:

<img width="1913" alt="image" src="https://github.com/user-attachments/assets/cdcaa9d2-4bf5-42db-bd49-ed7e5df83b58">

And here is the after results:

<img width="1913" alt="image" src="https://github.com/user-attachments/assets/4197043c-002f-4ac2-9bf7-28a5e0c34961">

Is this what you meant?

**Comment by esseti** [comment]
Oh, that's great! i thought  i've to do some api calls or somethings.

**Comment by bvanelli** [comment]
I'll leave this issue open until I write some documentation on how to modify existing transactions.
