### ISSUE TITLE
Read Accounts Notes

### ISSUE THREAD

**Issue by tcpr1** [bvanelli/actualpy#63]
### Description

I could not find how to query an account's note via actualpy, but I have seen someone who said he did it with the official api on discord. 

Is it possible to implement? 

Below, the code example he have posted, I don't know if it is helpful:

```
getAccountNote: async function (account) {
    const notes = await api.runQuery(
      api.q('notes')
        .filter({ id: `account-${account.id}` })
        .select('*')
      );
    if (notes.data.length && notes.data[0].note) {
      return notes.data[0].note;
    }
    return undefined;
  },
```

Thank you!

**Comment by bvanelli** [comment]
Accounts don't have notes as far as I remember, do you mean transaction notes?

Maybe show what exactly you want to retrieve from the database. With the sqlalchemy wrapper you can read pretty much anything that has a model.

**Comment by tcpr1** [comment]
I mean this field displayed there:

![image](https://github.com/user-attachments/assets/bb8165a3-36e3-46a6-a83d-a600c367b812)

**Comment by bvanelli** [comment]
Thanks for the report, I believe this might be an old implementation that I missed because the weird foreign key implemented:

<img width="927" alt="image" src="https://github.com/user-attachments/assets/ac668ea7-4a91-490b-8241-403c8c94288f">

Anyways, you may now use `Accounts.notes` to access that field:

```python
from actual import Actual
from actual.queries import get_accounts

with Actual(base_url="http://localhost:5006", password="mypass", file="CSV Importer") as actual:
    accounts = get_accounts(actual.session)
    for a in accounts:
        print(f"Notes for {a.name} are: {a.notes}")
```

For me, it prints:

```
Notes for Current Checking Account are: This are my notes for Current Checking Account
Notes for Current Savings Account are: These are my notes for Current Savings Account
Notes for Current Cash in Wallet are: These are my notes for Current Cash in Wallet
Notes for No notes are: None
```

Let me know if it works for you

**Comment by tcpr1** [comment]
It works, thank you!
