### ISSUE TITLE
Category from budgets should be scoped to the filtered month

### ISSUE THREAD

**Issue by raiyni** [bvanelli/actualpy#90]
### Description

I'd think something like

```python

budget = get_budget(actual.session, datetime.date.today(), 'Online Shopping')
LOGGER.debug("%s", budget.category.balance)
```

Would only include transactions from the filtered month instead of every transaction

**Comment by bvanelli** [comment]
Makes, since, it's actually a bug from my side that I do not currently do that, I'll fix it soon.

**Comment by bvanelli** [comment]
It was actually missing, checkout #91
